# Generated by Django 4.2.10 on 2025-11-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id_men', models.AutoField(primary_key=True, serialize=False)),
                ('rem_men', models.CharField(max_length=200)),
                ('em_men', models.EmailField(max_length=254)),
                ('tel_men', models.CharField(max_length=20)),
                ('tip_men', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fec_env', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
