# Generated by Django 4.2.10 on 2025-11-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id_det', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_fac', models.AutoField(primary_key=True, serialize=False)),
                ('num_fac', models.CharField(max_length=50, unique=True)),
                ('fec_emi', models.DateField(auto_now_add=True)),
                ('tot_fac', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_ord', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ord', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_rep', models.AutoField(primary_key=True, serialize=False)),
                ('tip_rep', models.CharField(max_length=100)),
                ('fec_gen', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('id_fac_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.factura')),
            ],
        ),
    ]
