# Generated by Django 4.2.10 on 2025-11-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='id_usu_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='id_usu_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_ord_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empleado.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='id_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='id_ord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='empleado.ordencompra'),
        ),
    ]
