# Generated by Django 4.2.10 on 2025-11-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cat', models.CharField(max_length=100)),
                ('des_cat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('nom_med', models.CharField(max_length=200)),
                ('des_med', models.TextField(blank=True, null=True)),
                ('pre_med', models.DecimalField(decimal_places=2, max_digits=10)),
                ('med_usu', models.CharField(max_length=200)),
                ('img_med', models.ImageField(blank=True, null=True, upload_to='medicamentos/')),
                ('id_cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='medicamentos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id_lot', models.AutoField(primary_key=True, serialize=False)),
                ('fec_ven', models.DateField()),
                ('cant_dis', models.PositiveIntegerField()),
                ('id_med_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='medicamentos.medicamento')),
            ],
        ),
    ]
