# Generated by Django 4.2.10 on 2025-11-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inv', models.AutoField(primary_key=True, serialize=False)),
                ('sto_act', models.PositiveIntegerField()),
                ('sto_min', models.PositiveIntegerField()),
                ('sto_max', models.PositiveIntegerField()),
                ('fec_act', models.DateTimeField(auto_now=True)),
                ('mot_act', models.TextField()),
                ('id_med_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicamentos.medicamento')),
            ],
        ),
    ]
