# Generated by Django 4.2.10 on 2025-11-07 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nom_rol', models.CharField(max_length=50)),
                ('desc_rol', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usu', models.CharField(max_length=100)),
                ('ape_usu', models.CharField(max_length=100)),
                ('cor_usu', models.EmailField(max_length=254, unique=True)),
                ('con_usu', models.CharField(max_length=255)),
                ('tel_usu', models.CharField(blank=True, max_length=20, null=True)),
                ('tip_doc', models.CharField(max_length=20)),
                ('num_doc', models.CharField(max_length=20, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('img_usu', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_rol_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
