# Generated by Django 4.2.10 on 2025-11-07 21:08

from django.db import migrations, models
import django.utils.timezone
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='con_usu',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_rol_fk',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ape_usu',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cor_usu',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img_usu',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nom_usu',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='num_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tel_usu',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tip_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios_usuario',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
